import type { BitrefillProduct } from "@/types/bitrefill";

export const MOCK_PRODUCTS: BitrefillProduct[] = [
  {
    id: "amazon-us",
    name: "Amazon US",
    description: "Shop millions of products on Amazon.com",
    country: "US",
    category: "e-commerce",
    currency: "USD",
    denominations: [10, 25, 50, 100, 200],
    supportedCrypto: ["ETH", "BTC", "USDT"],
    discount: 0.02,
    inStock: true,
  },
  {
    id: "steam-us",
    name: "Steam Wallet",
    description: "Add funds to your Steam wallet for games and DLC",
    country: "US",
    category: "gaming",
    currency: "USD",
    denominations: [10, 20, 50, 100],
    supportedCrypto: ["ETH", "BTC", "USDT"],
    discount: 0.03,
    inStock: true,
  },
  {
    id: "netflix-us",
    name: "Netflix",
    description: "Stream movies and TV shows worldwide",
    country: "US",
    category: "entertainment",
    currency: "USD",
    denominations: [15, 30, 60],
    supportedCrypto: ["ETH", "BTC"],
    discount: 0,
    inStock: true,
  },
  {
    id: "uber-us",
    name: "Uber",
    description: "Rides and Uber Eats delivery",
    country: "US",
    category: "travel",
    currency: "USD",
    denominations: [25, 50, 100],
    supportedCrypto: ["ETH", "BTC", "USDT"],
    discount: 0.01,
    inStock: true,
  },
  {
    id: "spotify-us",
    name: "Spotify Premium",
    description: "Music streaming without ads",
    country: "US",
    category: "entertainment",
    currency: "USD",
    denominations: [10, 30, 60],
    supportedCrypto: ["ETH", "BTC"],
    discount: 0,
    inStock: true,
  },
  {
    id: "google-play-us",
    name: "Google Play",
    description: "Apps, games, movies, and more from Google Play Store",
    country: "US",
    category: "gaming",
    currency: "USD",
    denominations: [10, 25, 50, 100],
    supportedCrypto: ["ETH", "BTC", "USDT"],
    discount: 0.01,
    inStock: true,
  },
  {
    id: "jd-cn",
    name: "京东 E卡",
    description: "京东商城购物卡，可购买自营商品",
    country: "CN",
    category: "e-commerce",
    currency: "CNY",
    denominations: [50, 100, 200, 500, 1000],
    supportedCrypto: ["ETH", "BTC", "USDT", "TRX"],
    discount: 0.02,
    inStock: true,
  },
  {
    id: "meituan-cn",
    name: "美团外卖",
    description: "美团外卖红包，点外卖更优惠",
    country: "CN",
    category: "food",
    currency: "CNY",
    denominations: [20, 50, 100, 200],
    supportedCrypto: ["ETH", "USDT", "TRX"],
    discount: 0.03,
    inStock: true,
  },
  {
    id: "china-mobile-cn",
    name: "中国移动话费",
    description: "中国移动手机话费充值",
    country: "CN",
    category: "phone-topup",
    currency: "CNY",
    denominations: [30, 50, 100, 200, 300],
    supportedCrypto: ["ETH", "BTC", "USDT", "TRX"],
    discount: 0.01,
    inStock: true,
  },
  {
    id: "china-unicom-cn",
    name: "中国联通话费",
    description: "中国联通手机话费充值",
    country: "CN",
    category: "phone-topup",
    currency: "CNY",
    denominations: [30, 50, 100, 200],
    supportedCrypto: ["ETH", "USDT", "TRX"],
    discount: 0.01,
    inStock: true,
  },
  {
    id: "netease-music-cn",
    name: "网易云音乐VIP",
    description: "网易云音乐会员充值",
    country: "CN",
    category: "entertainment",
    currency: "CNY",
    denominations: [15, 30, 88, 128],
    supportedCrypto: ["ETH", "USDT", "TRX"],
    discount: 0.05,
    inStock: true,
  },
  {
    id: "steam-cn",
    name: "Steam 中国区",
    description: "Steam 中国区钱包充值",
    country: "CN",
    category: "gaming",
    currency: "CNY",
    denominations: [30, 50, 100, 200, 500],
    supportedCrypto: ["ETH", "BTC", "USDT", "TRX"],
    discount: 0.02,
    inStock: true,
  },
  {
    id: "eleme-cn",
    name: "饿了么",
    description: "饿了么外卖红包充值",
    country: "CN",
    category: "food",
    currency: "CNY",
    denominations: [20, 50, 100],
    supportedCrypto: ["ETH", "USDT", "TRX"],
    discount: 0.02,
    inStock: true,
  },
  {
    id: "apple-us",
    name: "Apple Gift Card",
    description: "Use for App Store, Apple Music, iCloud, and more",
    country: "US",
    category: "entertainment",
    currency: "USD",
    denominations: [10, 25, 50, 100],
    supportedCrypto: ["ETH", "BTC", "USDT"],
    discount: 0,
    inStock: true,
  },
  {
    id: "playstation-us",
    name: "PlayStation Store",
    description: "PS5 and PS4 games, add-ons, and subscriptions",
    country: "US",
    category: "gaming",
    currency: "USD",
    denominations: [10, 25, 50, 100],
    supportedCrypto: ["ETH", "BTC"],
    discount: 0.01,
    inStock: true,
  },
  {
    id: "taobao-cn",
    name: "淘宝/天猫购物卡",
    description: "淘宝天猫通用购物卡",
    country: "CN",
    category: "e-commerce",
    currency: "CNY",
    denominations: [50, 100, 200, 500],
    supportedCrypto: ["ETH", "USDT", "TRX"],
    discount: 0.01,
    inStock: true,
  },
  {
    id: "didi-cn",
    name: "滴滴出行",
    description: "滴滴打车优惠券充值",
    country: "CN",
    category: "travel",
    currency: "CNY",
    denominations: [50, 100, 200],
    supportedCrypto: ["ETH", "USDT", "TRX"],
    discount: 0.02,
    inStock: true,
  },
  {
    id: "esim-japan",
    name: "Japan eSIM 5GB",
    description: "High-speed data eSIM for Japan travel. 30-day validity, 5GB data.",
    country: "JP",
    category: "esim",
    currency: "USD",
    denominations: [5, 10, 20],
    supportedCrypto: ["ETH", "BTC", "USDT"],
    discount: 0,
    inStock: true,
  },
  {
    id: "esim-thailand",
    name: "Thailand eSIM 10GB",
    description: "High-speed data eSIM for Thailand. 15-day validity, 10GB data.",
    country: "TH",
    category: "esim",
    currency: "USD",
    denominations: [8, 15, 25],
    supportedCrypto: ["ETH", "BTC", "USDT"],
    discount: 0.05,
    inStock: true,
  },
  {
    id: "esim-korea",
    name: "South Korea eSIM 5GB",
    description: "High-speed data eSIM for South Korea. 30-day validity, 5GB data.",
    country: "KR",
    category: "esim",
    currency: "USD",
    denominations: [6, 12, 20],
    supportedCrypto: ["ETH", "BTC", "USDT"],
    discount: 0,
    inStock: true,
  },
  {
    id: "esim-europe",
    name: "Europe eSIM 10GB",
    description: "Roaming data eSIM covering 30+ European countries. 30-day validity.",
    country: "ALL",
    category: "esim",
    currency: "USD",
    denominations: [10, 20, 35],
    supportedCrypto: ["ETH", "BTC", "USDT"],
    discount: 0.03,
    inStock: true,
  },
  {
    id: "esim-usa",
    name: "USA eSIM 10GB",
    description: "High-speed data eSIM for the United States. 30-day validity, 10GB.",
    country: "US",
    category: "esim",
    currency: "USD",
    denominations: [10, 20, 30],
    supportedCrypto: ["ETH", "BTC", "USDT"],
    discount: 0,
    inStock: true,
  },
  {
    id: "esim-singapore",
    name: "Singapore eSIM 5GB",
    description: "High-speed data eSIM for Singapore. 15-day validity, 5GB data.",
    country: "SG",
    category: "esim",
    currency: "USD",
    denominations: [5, 10, 18],
    supportedCrypto: ["ETH", "BTC", "USDT"],
    discount: 0,
    inStock: true,
  },
  {
    id: "esim-global",
    name: "Global eSIM 5GB",
    description: "Worldwide roaming eSIM covering 100+ countries. 30-day validity.",
    country: "ALL",
    category: "esim",
    currency: "USD",
    denominations: [15, 30, 50],
    supportedCrypto: ["ETH", "BTC", "USDT"],
    discount: 0.02,
    inStock: true,
  },
  {
    id: "xbox-us",
    name: "Xbox Gift Card",
    description: "Games, add-ons, and subscriptions for Xbox",
    country: "US",
    category: "gaming",
    currency: "USD",
    denominations: [10, 25, 50, 100],
    supportedCrypto: ["ETH", "BTC", "USDT"],
    discount: 0.01,
    inStock: true,
  },
  {
    id: "esim-turkey",
    name: "Turkey eSIM 5GB",
    description: "High-speed data eSIM for Turkey. 30-day validity, 5GB data.",
    country: "TR",
    category: "esim",
    currency: "USD",
    denominations: [6, 12, 20],
    supportedCrypto: ["ETH", "BTC", "USDT"],
    discount: 0,
    inStock: true,
  },
  {
    id: "esim-hongkong",
    name: "Hong Kong eSIM 5GB",
    description: "High-speed data eSIM for Hong Kong. 15-day validity, 5GB data.",
    country: "HK",
    category: "esim",
    currency: "USD",
    denominations: [5, 10, 18],
    supportedCrypto: ["ETH", "BTC", "USDT"],
    discount: 0,
    inStock: true,
  },
  {
    id: "esim-vietnam",
    name: "Vietnam eSIM 10GB",
    description: "High-speed data eSIM for Vietnam. 30-day validity, 10GB data.",
    country: "VN",
    category: "esim",
    currency: "USD",
    denominations: [5, 10, 18],
    supportedCrypto: ["ETH", "BTC", "USDT"],
    discount: 0.05,
    inStock: true,
  },
  {
    id: "esim-malaysia",
    name: "Malaysia eSIM 5GB",
    description: "High-speed data eSIM for Malaysia. 15-day validity, 5GB data.",
    country: "MY",
    category: "esim",
    currency: "USD",
    denominations: [5, 10, 16],
    supportedCrypto: ["ETH", "BTC", "USDT"],
    discount: 0,
    inStock: true,
  },
];

export const COUNTRIES = [
  { code: "CN", name: "China 🇨🇳" },
  { code: "US", name: "United States 🇺🇸" },
  { code: "ALL", name: "All Countries 🌍" },
];

export const CATEGORIES: { value: string; label: string }[] = [
  { value: "all", label: "All" },
  { value: "e-commerce", label: "E-Commerce" },
  { value: "food", label: "Food" },
  { value: "gaming", label: "Gaming" },
  { value: "phone-topup", label: "Phone Top-up" },
  { value: "entertainment", label: "Entertainment" },
  { value: "travel", label: "Travel" },
        { value: "esim", label: "eSIM" },
];

// Mock exchange rates (1 unit of crypto = X USD)
export const MOCK_EXCHANGE_RATES: Record<string, number> = {
  ETH: 3500,
  BTC: 105000,
  USDT: 1,
  TRX: 0.25,
};

// CNY to USD rate
export const CNY_TO_USD = 0.138;
